trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  -stage:
   displayName: build
   pool: ubantu-latest
   jobs:
     -job: job_1
      steps:
        -script: echo 'i am in job1,step1'
     -job: job_2
      steps: 
        -script: echo 'i am in job2,step1'

  -stage: 
   displayName: deploy
   jobs: 
      -job: job_1
       steps:
        -script: echo 'i am in job1,step1' 
    
